persistence:
    size: "500Mi"

version: "v3.1.8"

image: "registry.nscloud:5000/kunkka/saas/nscloud-dkron-api:3.1.8"

log:
    level: "info"

server:
    replicas: 3
    bootstrapExpected: 2

agent:
    replicas: 1

nodeSelector: {}
tolerations: []
