version: "v3.1.8"

image: "registry.nscloud:5000/kunkka/saas/nscloud-dkron-api:3.1.8"

log:
    level: "info"

server:
    replicas: 3
    bootstrapExpected: 1
    storageClass: 'rook-ceph-block'
    persistenceSize: '2Gi'

agent:
    replicas: 1
    storageClass: 'rook-ceph-block'
    persistenceSize: '2Gi'

nodeSelector: {}
tolerations: []
