apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: {{ .Chart.Name }}-dkron-cluster-discovery
    namespace: {{ .Release.Namespace }}
subjects:
    -   kind: ServiceAccount
        name: dkron
        namespace: {{ .Release.Namespace }}
roleRef:
    kind: Role
    name: dkron-discovery-manager
    apiGroup: rbac.authorization.k8s.io
