apiVersion: v1
kind: Service
metadata:
    name: dkron
    namespace: {{ .Release.Namespace }}
spec:
    type: NodePort
    selector:
        app: dkron
    ports:
        -   protocol: TCP
            name: serf
            port: 8946
        -   protocol: TCP
            name: grpc
            port: 6868
